#!/bin/bash
cp implementation/system.bit ../bit_files/baopoco_2011_Oct_20_1858.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/baopoco_2011_Oct_20_1858.bof
