#!/bin/bash
cp implementation/system.bit ../bit_files/roachf_1024_bao_2012_Jun_27_2138.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/roachf_1024_bao_2012_Jun_27_2138.bof
