#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/scratch/zaki/workspace/baobab/roachf_1024_bao/XPS_ROACH_base/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /scratch/Xilinx/13.3/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex5

DEVICE = xc5vsx95tff1136-1

INTSTYLE = default

LANGUAGE = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

EPB_OPB_BRIDGE_INST_BOOTLOOP = $(BOOTLOOP_DIR)/epb_opb_bridge_inst.elf

BRAMINIT_ELF_IMP_FILES = $(EPB_OPB_BRIDGE_INST_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe epb_opb_bridge_inst $(EPB_OPB_BRIDGE_INST_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(EPB_OPB_BRIDGE_INST_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe epb_opb_bridge_inst $(EPB_OPB_BRIDGE_INST_BOOTLOOP)

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = pcores/adc_interface_v1_01_a/netlist/adc_fifo.edn \
pcores/adc_interface_v1_01_a/netlist/adc_fifo_fifo_generator_v2_2_xst_1.ngc \
pcores/adc_interface_v1_01_a/netlist/adc_fifo.edn \
pcores/adc_interface_v1_01_a/netlist/adc_fifo_fifo_generator_v2_2_xst_1.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
pcores/xaui_phy_v1_00_a/netlist/xaui_v7_2.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
pcores/xaui_phy_v1_00_a/netlist/xaui_v7_2.ngc \
pcores/roach_infrastructure_v1_00_a/hdl/verilog/roach_infrastructure.v \
pcores/reset_block_v1_00_a/hdl/verilog/reset_block.v \
pcores/epb_opb_bridge_v1_00_a/hdl/verilog/epb_opb_bridge.v \
pcores/epb_infrastructure_v1_00_a/hdl/verilog/epb_infrastructure.v \
pcores/sys_block_v1_00_a/hdl/verilog/sys_block.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/xaui_infrastructure.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/transceiver_bank.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/transceiver.v \
pcores/opb_adccontroller_v1_00_a/hdl/verilog/adc_config_mux.v \
pcores/opb_adccontroller_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/opb_adccontroller_v1_00_a/hdl/vhdl/opb_adccontroller.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/proc_common_pkg.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/family.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_muxcy.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_gate.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/counter_bit.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/counter.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/inferred_lut4.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/srl_fifo2.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter_bit.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter_top.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_occ_counter.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_occ_counter_top.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_adder_bit.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_adder.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pf_dpram_select.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/srl16_fifo.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pselect.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/valid_be.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/ld_arith_reg.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/mux_onehot.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/down_counter.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/ipif_pkg.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/ipif_steer.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/direct_path_cntr_ai.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/interrupt_control_v1_00_a/hdl/vhdl/interrupt_control.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/pf_dly1_mux.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/ipif_control_wr.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/wrpfifo_dp_cntl.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/wrpfifo_top.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/ipif_control_rd.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/rdpfifo_dp_cntl.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/rdpfifo_top.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/reset_mir.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/brst_addr_cntr.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_flex_addr_cntr.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/brst_addr_cntr_reg.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_be_gen.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/srl_fifo3.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/write_buffer.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_bam.vhd \
/scratch/Xilinx/13.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_ipif.vhd \
pcores/opb_register_ppc2simulink_v1_00_a/hdl/verilog/opb_register_ppc2simulink.v \
pcores/adc_interface_v1_01_a/hdl/vhdl/adc_fifo.vhd \
pcores/adc_interface_v1_01_a/hdl/vhdl/ddr_input.vhd \
pcores/adc_interface_v1_01_a/hdl/vhdl/adc_interface.vhd \
pcores/gpio_simulink2ext_v1_00_a/hdl/vhdl/gpio_simulink2ext.vhd \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/arp_cache.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/cpu_buffer.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/kat_ten_gb_eth.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/opb_attach.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_bram.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_dist.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_rx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_tx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_fifo_ext.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/ten_gig_eth_mac.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_rx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_tx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_hard_crc.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_phy.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_v7_2.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/deskew_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/fix_term.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_deskew.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_rx.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_sync.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_tx.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/sync_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/tx_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_kat.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_kat.vh \
pcores/opb_register_simulink2ppc_v1_00_a/hdl/verilog/opb_register_simulink2ppc.v \
pcores/bram_if_v1_00_a/hdl/vhdl/bram_if.vhd \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdr_controller.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_top.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_infrastructure.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy_bit_align.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy_bit_correct.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy_bit_train.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy_burst_align.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_phy_sm.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_rd.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_wr.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/opb_qdr_sniffer.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/async_qdr_interface.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/qdr_config.v

WRAPPER_NGC_FILES = implementation/infrastructure_inst_wrapper.ngc \
implementation/reset_block_inst_wrapper.ngc \
implementation/opb0_wrapper.ngc \
implementation/epb_opb_bridge_inst_wrapper.ngc \
implementation/epb_infrastructure_inst_wrapper.ngc \
implementation/sys_block_inst_wrapper.ngc \
implementation/xaui_infrastructure_inst_wrapper.ngc \
implementation/opb_adccontroller_0_wrapper.ngc \
implementation/roachf_1024_bao_ant_base_wrapper.ngc \
implementation/roachf_1024_bao_feng_ctl_wrapper.ngc \
implementation/roachf_1024_bao_fft_shift_wrapper.ngc \
implementation/roachf_1024_bao_gbe_sw_port_wrapper.ngc \
implementation/roachf_1024_bao_gpu_ip_wrapper.ngc \
implementation/roachf_1024_bao_gpu_port_wrapper.ngc \
implementation/roachf_1024_bao_ip_base_wrapper.ngc \
implementation/roachf_1024_bao_my_ip_wrapper.ngc \
implementation/roachf_1024_bao_adc_s_adc_wrapper.ngc \
implementation/roachf_1024_bao_adc_s_adc1_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant0_addr_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant0_gain_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant1_addr_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant1_gain_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant2_addr_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant2_gain_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant3_addr_wrapper.ngc \
implementation/roachf_1024_bao_eq_quant3_gain_wrapper.ngc \
implementation/roachf_1024_bao_leds_led1_arm_wrapper.ngc \
implementation/roachf_1024_bao_leds_led2_sync_wrapper.ngc \
implementation/roachf_1024_bao_leds_led4_eq_clip_wrapper.ngc \
implementation/roachf_1024_bao_delay_values_wrapper.ngc \
implementation/roachf_1024_bao_gpu_gbe2_wrapper.ngc \
implementation/xaui_phy_2_wrapper.ngc \
implementation/roachf_1024_bao_gpu_mcnt_lsb_wrapper.ngc \
implementation/roachf_1024_bao_gpu_mcnt_msb_wrapper.ngc \
implementation/roachf_1024_bao_input_selector_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loop_cnt_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loop_err_cnt_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loopback_mux_gbe_over_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loopback_mux_gbe_und_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loopback_mux_lb_over_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loopback_mux_lb_und_wrapper.ngc \
implementation/roachf_1024_bao_loopback_loopback_fifo_lb_err_cnt_wrapper.ngc \
implementation/roachf_1024_bao_loopback_rx_cnt_wrapper.ngc \
implementation/roachf_1024_bao_loopback_rx_err_cnt_wrapper.ngc \
implementation/roachf_1024_bao_loopback_rx_pkt_fifo_santa_2big_wrapper.ngc \
implementation/roachf_1024_bao_loopback_rx_pkt_fifo_santa_2small_wrapper.ngc \
implementation/roachf_1024_bao_loopback_rx_pkt_fifo_gbe_err_cnt_wrapper.ngc \
implementation/roachf_1024_bao_seed_data_wrapper.ngc \
implementation/roachf_1024_bao_status_gbe_gpu_wrapper.ngc \
implementation/roachf_1024_bao_status_gbe_sw_wrapper.ngc \
implementation/roachf_1024_bao_status_swgbe_bframe_wrapper.ngc \
implementation/roachf_1024_bao_status_swgbe_oflow_wrapper.ngc \
implementation/roachf_1024_bao_status_swgbe_orun_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_addr_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_lsb_ramif_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_lsb_ramblk_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_lsb_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_msb_ramif_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_msb_ramblk_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_msb_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_oob_ramif_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_oob_ramblk_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_bram_oob_wrapper.ngc \
implementation/roachf_1024_bao_switch_10gbetxsnap_ctrl_wrapper.ngc \
implementation/roachf_1024_bao_switch_gbe3_wrapper.ngc \
implementation/xaui_phy_3_wrapper.ngc \
implementation/qdr0_controller_wrapper.ngc \
implementation/qdr0_sniffer_wrapper.ngc \
implementation/qdr1_controller_wrapper.ngc \
implementation/qdr1_sniffer_wrapper.ngc \
implementation/opb1_wrapper.ngc \
implementation/opb2opb_bridge_opb1_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
